# MA_DL : Codierung 64bit

In [2]:
!pip install facenet-pytorch # due to issues with the google cloud service

In [3]:
import torch
import torchvision.transforms as transforms
from torch.autograd import Variable
from torch import nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets
import torchvision.models as models
from PIL import Image

from facenet_pytorch import MTCNN, InceptionResnetV1

dtype = torch.cuda.FloatTensor

## Model

In [4]:
class MultiLabel(nn.Sequential):
    def __init__(self, input_dim=512, output_dim=64):
        super(MultiLabel, self).__init__()
        self.l1 = nn.Linear(input_dim, input_dim)
        self.l2 = nn.Linear(input_dim, input_dim)
        self.l5 = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        x = F.relu(self.l1(x))
        x = F.relu(self.l2(x))
        x = self.l5(x)
        return torch.sigmoid(x)

In [5]:
model = MultiLabel()
model.cuda()

MultiLabel(
  (l1): Linear(in_features=512, out_features=512, bias=True)
  (l2): Linear(in_features=512, out_features=512, bias=True)
  (l5): Linear(in_features=512, out_features=64, bias=True)
)

## Data

In [6]:
scaler = transforms.Resize((224, 224))
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
to_tensor = transforms.ToTensor()
to_image = transforms.ToPILImage()
transform = transforms.Compose([
    scaler, 
    to_tensor,
#    normalize
])

In [7]:
train_ds = datasets.ImageFolder('../../data/small_data/train/', transform=transform)
train_ds.idx_to_class = {i:c for c, i in train_ds.class_to_idx.items()}
train_dl = DataLoader(train_ds, batch_size=1, num_workers=4)

valid_ds = datasets.ImageFolder('../../data/small_data/valid/', transform=transform)
valid_ds.idx_to_class = {i:c for c, i in valid_ds.class_to_idx.items()}
valid_dl = DataLoader(valid_ds, batch_size=1, num_workers=4)

## Gesichtserkennung

In [9]:
mtcnn = MTCNN(
    image_size=160,
    thresholds=[0.6, 0.7, 0.7],
#        factor=0.709,
#        prewhiten=True,
    keep_all=True,
    device=torch.device('cuda')
    )

## Embeddings 

In [10]:
def get_vectors(imgs):
    # 2. Create a PyTorch Variable with the transformed image
    t_img = Variable(imgs).type(dtype)  
    
    # 3. Create a vector of zeros that will hold our feature vector
    #    The 'avgpool' layer has an output size of 512
    my_embedding = torch.zeros(imgs.shape[0], 512)    

    # 4. Define a function that will copy the output of a layer
    def copy_data(m, i, o):
      my_embedding.copy_(o.data.squeeze())    
    
    # 5. Attach that function to our selected layer
    h = layer.register_forward_hook(copy_data)    
    # 6. Run the model on our transformed image
    resnet(t_img)    
    # 7. Detach our copy function from the layer
    h.remove()    
    # 8. Return the feature vector
    return my_embedding

In [ ]:
# Alternativ resnet
vggf_resnet = InceptionResnetV1(pretrained='vggface2').eval()
img_embedding = vggf_resnet(img_cropped.unsqueeze(0))

In [11]:
# Load the pretrained model
resnet = models.resnet18(pretrained=True)
resnet.cuda()
# Use the model object to select the desired layer
layer = resnet._modules.get('avgpool')
_ = resnet.eval()

## Training

In [12]:
def calculate_mistakes(pred, target):
    #pred = pred[0]
#    print('calculating mistakes : ')
#    print('   pred: ' + str(pred.shape))
#    print('   target: ' + str(target.shape))
    
    mistakes = 0
    
    if len(pred) != len(target):
        raise Exception('sizes of both tensors must match')
        
    for x,y in zip(pred, target):
        if round(x.item()) != y.item():
            mistakes = mistakes + 1
        
    return mistakes

In [13]:
loss_func = nn.BCELoss() #MultiLabelSoftMarginLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2, weight_decay=1e-5) #weight_decay=1e-4 

In [12]:
import matplotlib.pyplot as plt

In [15]:
for d, t in train_dl:
    print(d.shape)
    print(d)
    
    

torch.Size([1, 3, 224, 224])
tensor([[[[0.0118, 0.0118, 0.0118,  ..., 0.0078, 0.0118, 0.0118],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.1922, 0.2078, 0.2392,  ..., 0.2392, 0.2431, 0.2471],
          [0.2353, 0.2275, 0.2392,  ..., 0.2431, 0.2471, 0.2510],
          [0.2588, 0.2431, 0.2392,  ..., 0.2431, 0.2471, 0.2510]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
          [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0039, 0.0039],
          ...,
          [0.1765, 0.1804, 0.1882,  ..., 0.1843, 0.1882, 0.1922],
          [0.2078, 0.1843, 0.1843,  ..., 0.1882, 0.1922, 0.1961],
          [0.2157, 0.1843, 0.1804,  ..., 0.1882, 0.1922, 0.1961]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0039, 0.0039, 0.0039,  ..., 0.0078, 0.0078, 0.0078],
          [0.

torch.Size([1, 3, 224, 224])
tensor([[[[0.7373, 0.7294, 0.7333,  ..., 0.4745, 0.4863, 0.4980],
          [0.7490, 0.7373, 0.7412,  ..., 0.4902, 0.5098, 0.5294],
          [0.7608, 0.7451, 0.7490,  ..., 0.5098, 0.5373, 0.5569],
          ...,
          [0.2039, 0.1490, 0.1059,  ..., 0.5686, 0.5490, 0.5490],
          [0.2157, 0.1451, 0.1137,  ..., 0.5765, 0.5569, 0.5412],
          [0.2157, 0.1451, 0.1137,  ..., 0.5804, 0.5647, 0.5451]],

         [[0.5412, 0.5373, 0.5451,  ..., 0.4706, 0.4824, 0.4902],
          [0.5529, 0.5451, 0.5569,  ..., 0.4863, 0.5059, 0.5216],
          [0.5647, 0.5529, 0.5647,  ..., 0.5059, 0.5333, 0.5529],
          ...,
          [0.2039, 0.1490, 0.1059,  ..., 0.6235, 0.5961, 0.5843],
          [0.2157, 0.1451, 0.1098,  ..., 0.6314, 0.6039, 0.5725],
          [0.2118, 0.1412, 0.1098,  ..., 0.6353, 0.6039, 0.5725]],

         [[0.2510, 0.2353, 0.2353,  ..., 0.2980, 0.3176, 0.3294],
          [0.2627, 0.2431, 0.2431,  ..., 0.3137, 0.3373, 0.3569],
          [0.

tensor([[[[0.3451, 0.3412, 0.3412,  ..., 0.7725, 0.7765, 0.7765],
          [0.3216, 0.3176, 0.3176,  ..., 0.7569, 0.7608, 0.7608],
          [0.2863, 0.2824, 0.2863,  ..., 0.7373, 0.7412, 0.7412],
          ...,
          [0.0196, 0.0235, 0.0196,  ..., 0.0588, 0.0510, 0.0510],
          [0.0235, 0.0196, 0.0118,  ..., 0.0627, 0.0549, 0.0549],
          [0.0275, 0.0235, 0.0118,  ..., 0.0627, 0.0549, 0.0549]],

         [[0.2392, 0.2353, 0.2314,  ..., 0.7490, 0.7529, 0.7569],
          [0.2157, 0.2118, 0.2078,  ..., 0.7412, 0.7490, 0.7490],
          [0.1882, 0.1804, 0.1804,  ..., 0.7294, 0.7373, 0.7373],
          ...,
          [0.0196, 0.0235, 0.0314,  ..., 0.0588, 0.0510, 0.0510],
          [0.0235, 0.0235, 0.0235,  ..., 0.0627, 0.0549, 0.0588],
          [0.0275, 0.0275, 0.0235,  ..., 0.0627, 0.0588, 0.0588]],

         [[0.1569, 0.1529, 0.1490,  ..., 0.6078, 0.6118, 0.6078],
          [0.1373, 0.1333, 0.1294,  ..., 0.5961, 0.6000, 0.6000],
          [0.1098, 0.1059, 0.1059,  ..., 0

tensor([[[[0.3490, 0.3490, 0.3490,  ..., 0.3216, 0.3216, 0.3216],
          [0.3647, 0.3608, 0.3569,  ..., 0.3255, 0.3255, 0.3255],
          [0.3804, 0.3765, 0.3686,  ..., 0.3333, 0.3294, 0.3294],
          ...,
          [0.2000, 0.2000, 0.1961,  ..., 0.1647, 0.1647, 0.1647],
          [0.1961, 0.1961, 0.1922,  ..., 0.1569, 0.1529, 0.1490],
          [0.1961, 0.1961, 0.1922,  ..., 0.1569, 0.1451, 0.1412]],

         [[0.2627, 0.2627, 0.2627,  ..., 0.2549, 0.2549, 0.2549],
          [0.2784, 0.2745, 0.2706,  ..., 0.2588, 0.2588, 0.2588],
          [0.2941, 0.2902, 0.2824,  ..., 0.2667, 0.2627, 0.2627],
          ...,
          [0.1765, 0.1765, 0.1725,  ..., 0.1451, 0.1451, 0.1451],
          [0.1725, 0.1725, 0.1686,  ..., 0.1373, 0.1333, 0.1294],
          [0.1725, 0.1725, 0.1686,  ..., 0.1373, 0.1255, 0.1216]],

         [[0.1725, 0.1725, 0.1725,  ..., 0.2157, 0.2157, 0.2157],
          [0.1882, 0.1843, 0.1843,  ..., 0.2196, 0.2196, 0.2196],
          [0.2118, 0.2078, 0.2000,  ..., 0

torch.Size([1, 3, 224, 224])
tensor([[[[0.0627, 0.0627, 0.0627,  ..., 0.1255, 0.1255, 0.1216],
          [0.0627, 0.0627, 0.0627,  ..., 0.1451, 0.1294, 0.1216],
          [0.0627, 0.0627, 0.0627,  ..., 0.1529, 0.1373, 0.1294],
          ...,
          [0.1373, 0.1412, 0.1373,  ..., 0.1686, 0.1882, 0.2000],
          [0.1412, 0.1412, 0.1373,  ..., 0.1647, 0.1843, 0.2039],
          [0.1373, 0.1373, 0.1373,  ..., 0.1647, 0.1843, 0.2000]],

         [[0.0784, 0.0784, 0.0784,  ..., 0.0784, 0.0784, 0.0745],
          [0.0784, 0.0784, 0.0784,  ..., 0.1059, 0.0863, 0.0784],
          [0.0784, 0.0784, 0.0784,  ..., 0.1176, 0.0980, 0.0941],
          ...,
          [0.1098, 0.1137, 0.1137,  ..., 0.1608, 0.1804, 0.1882],
          [0.1098, 0.1098, 0.1137,  ..., 0.1608, 0.1804, 0.1961],
          [0.1137, 0.1137, 0.1137,  ..., 0.1608, 0.1804, 0.1961]],

         [[0.0824, 0.0824, 0.0824,  ..., 0.0784, 0.0784, 0.0745],
          [0.0824, 0.0824, 0.0824,  ..., 0.1020, 0.0824, 0.0745],
          [0.

torch.Size([1, 3, 224, 224])
tensor([[[[0.1137, 0.1216, 0.1294,  ..., 0.2392, 0.1804, 0.1490],
          [0.0941, 0.0980, 0.1020,  ..., 0.2118, 0.1569, 0.1255],
          [0.0706, 0.0784, 0.0863,  ..., 0.1804, 0.1216, 0.0863],
          ...,
          [0.1255, 0.1255, 0.1255,  ..., 0.1216, 0.1255, 0.1255],
          [0.1373, 0.1333, 0.1333,  ..., 0.1294, 0.1333, 0.1333],
          [0.1412, 0.1373, 0.1333,  ..., 0.1294, 0.1451, 0.1490]],

         [[0.1216, 0.1333, 0.1451,  ..., 0.2510, 0.1961, 0.1725],
          [0.1176, 0.1176, 0.1255,  ..., 0.2353, 0.1882, 0.1647],
          [0.1098, 0.1176, 0.1255,  ..., 0.2196, 0.1725, 0.1412],
          ...,
          [0.1529, 0.1529, 0.1529,  ..., 0.2039, 0.2078, 0.2039],
          [0.1647, 0.1608, 0.1608,  ..., 0.2039, 0.2118, 0.2078],
          [0.1686, 0.1647, 0.1608,  ..., 0.2000, 0.2196, 0.2196]],

         [[0.0667, 0.0667, 0.0745,  ..., 0.1686, 0.1216, 0.0941],
          [0.0549, 0.0471, 0.0510,  ..., 0.1529, 0.1098, 0.0824],
          [0.

torch.Size([1, 3, 224, 224])
tensor([[[[0.0275, 0.0353, 0.0314,  ..., 0.8510, 0.8471, 0.8353],
          [0.0275, 0.0314, 0.0314,  ..., 0.8392, 0.8314, 0.8196],
          [0.0235, 0.0314, 0.0314,  ..., 0.8196, 0.8078, 0.8000],
          ...,
          [0.9294, 0.9294, 0.9294,  ..., 0.9765, 0.9765, 0.9765],
          [0.9294, 0.9294, 0.9294,  ..., 0.9765, 0.9765, 0.9765],
          [0.9294, 0.9294, 0.9294,  ..., 0.9765, 0.9765, 0.9765]],

         [[0.0392, 0.0471, 0.0510,  ..., 0.8824, 0.8706, 0.8549],
          [0.0392, 0.0510, 0.0510,  ..., 0.8706, 0.8549, 0.8392],
          [0.0392, 0.0471, 0.0510,  ..., 0.8588, 0.8392, 0.8235],
          ...,
          [0.9922, 0.9922, 0.9922,  ..., 1.0000, 1.0000, 1.0000],
          [0.9922, 0.9922, 0.9922,  ..., 1.0000, 1.0000, 1.0000],
          [0.9922, 0.9922, 0.9922,  ..., 1.0000, 1.0000, 1.0000]],

         [[0.0588, 0.0667, 0.0667,  ..., 0.8039, 0.7843, 0.7686],
          [0.0667, 0.0745, 0.0706,  ..., 0.8039, 0.7804, 0.7608],
          [0.

tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0314, 0.0314, 0.0314,  ..., 0.0353, 0.0314, 0.0235],
          [0.0314, 0.0275, 0.0275,  ..., 0.0235, 0.0235, 0.0196],
          [0.0314, 0.0275, 0.0275,  ..., 0.0196, 0.0196, 0.0196]],

         [[0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0314, 0.0314, 0.0314,  ..., 0.0314, 0.0314, 0.0235],
          [0.0314, 0.0275, 0.0275,  ..., 0.0196, 0.0235, 0.0196],
          [0.0314, 0.0275, 0.0275,  ..., 0.0157, 0.0196, 0.0196]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.0078, 0.0078, 0.0078],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0

tensor([[[[0.8902, 0.8902, 0.8980,  ..., 0.9882, 0.9843, 0.9843],
          [0.9059, 0.9059, 0.9137,  ..., 0.9882, 0.9882, 0.9882],
          [0.9333, 0.9333, 0.9373,  ..., 0.9961, 0.9961, 0.9961],
          ...,
          [0.6314, 0.6706, 0.6824,  ..., 0.0196, 0.0196, 0.0196],
          [0.6157, 0.6549, 0.6627,  ..., 0.0196, 0.0235, 0.0235],
          [0.5961, 0.6314, 0.6353,  ..., 0.0196, 0.0235, 0.0235]],

         [[0.8314, 0.8314, 0.8353,  ..., 1.0000, 0.9961, 0.9961],
          [0.8471, 0.8471, 0.8510,  ..., 0.9961, 0.9961, 0.9961],
          [0.8745, 0.8745, 0.8745,  ..., 1.0000, 0.9961, 0.9961],
          ...,
          [0.4588, 0.5020, 0.5255,  ..., 0.0627, 0.0627, 0.0627],
          [0.4314, 0.4784, 0.5020,  ..., 0.0627, 0.0667, 0.0667],
          [0.4039, 0.4510, 0.4706,  ..., 0.0627, 0.0667, 0.0667]],

         [[0.7176, 0.7176, 0.7294,  ..., 0.9608, 0.9569, 0.9569],
          [0.7333, 0.7333, 0.7412,  ..., 0.9451, 0.9451, 0.9451],
          [0.7608, 0.7608, 0.7647,  ..., 0

In [16]:
epochs = 1000
for e in range(epochs):
    print("======================")
    print("Epoch : " + str(e))
    epoch_loss = 0
    epoch_mistakes = 0
    train_size = len(train_dl)
    
    # activate train mode
    model.train()

    for index, (data, target) in enumerate(train_dl):
        
        faces, prob = mtcnn(to_image(data[0]), return_prob=True)
 
 #       if faces is None:
 #           print('no face')
 #           continue
 #       else:
 #           print('face found')
                
        target_t = torch.cuda.FloatTensor([int(x) for x in train_ds.idx_to_class[target[0].item()]])

        emb = get_vectors(faces)    
        data_v   = Variable(emb[0], requires_grad=False).type(dtype)
        target_v = Variable(target_t, requires_grad=False).type(dtype)
        print(data_v)
        
        # forward
#        print('datav: ' + str(data_v.shape))
        pred = model.forward(data_v)
#        print('pred: ' + str(pred.shape))
        # zero grads
        optimizer.zero_grad()
        # calculate loss
        loss = loss_func(pred, target_v.float())
        epoch_loss = epoch_loss + loss
        # back prop
        loss.backward()
        optimizer.step()
        
        epoch_mistakes = epoch_mistakes + calculate_mistakes(pred, target_t)
        
    print("Train loss : " + str(epoch_loss.item()))
    print("Average errors : " + str(epoch_mistakes/train_size))
    
    # activate eval mode
    model.eval()
    
    valid_loss = 0
    valid_mistakes = 0
    valid_size = len(valid_dl)
    for index, (data, target) in enumerate(valid_dl):
        faces, prob = mtcnn(to_image(data[0]), return_prob=True)
        target_t = torch.FloatTensor([int(x) for x in valid_ds.idx_to_class[target[0].item()]])
        
        emb = get_vectors(faces) 
        data_v   = Variable(emb[0], requires_grad=False).type(dtype)
        target_v = Variable(target_t, requires_grad=False).type(dtype)

        pred = model.forward(data_v)
        loss = loss_func(pred, target_v.float())
        valid_loss = valid_loss + loss
        valid_mistakes = valid_mistakes + calculate_mistakes(pred, target_t)
        
        
    print("Valid loss : " + str(valid_loss.item()))
    print("Average valid errors : " + str(valid_mistakes/valid_size))

Epoch : 0
tensor([2.5640e-01, 1.3146e+00, 1.5079e+00, 3.1035e-01, 2.0382e-03, 1.3857e-01,
        5.9693e-01, 6.1075e-01, 0.0000e+00, 0.0000e+00, 1.1364e+00, 1.3891e+00,
        1.5071e-02, 1.4342e-02, 4.7746e-01, 1.7059e+00, 1.0079e+00, 4.1452e-01,
        8.5286e-03, 9.8521e-01, 1.8991e-03, 1.2539e-01, 0.0000e+00, 4.7227e-01,
        3.2950e-01, 0.0000e+00, 4.9375e-02, 2.1689e-01, 1.9052e-01, 1.9319e-01,
        1.4432e-01, 2.7139e-01, 3.9479e-01, 1.2855e+00, 2.2850e-01, 1.9375e-01,
        1.1812e+00, 2.1384e-01, 4.9124e+00, 0.0000e+00, 1.6862e+00, 2.8418e+00,
        6.1418e-01, 8.8550e-04, 2.1597e+00, 1.9472e+00, 2.1129e-01, 2.2915e+00,
        1.8560e+00, 1.3147e+00, 5.7089e-01, 2.8221e+00, 8.1840e-02, 2.1415e+00,
        1.2533e-01, 1.1812e-01, 7.0330e-02, 5.4673e-01, 1.3466e+00, 2.4492e+00,
        2.7128e-02, 7.1513e-01, 2.0384e+00, 1.1267e+00, 2.1586e-01, 9.7823e-01,
        1.4201e+00, 1.3790e-01, 1.6494e-01, 8.1740e-01, 6.1346e-01, 2.9539e-01,
        8.1662e-02, 3.6244e+00

tensor([2.0979e-01, 1.4664e+00, 1.1818e+00, 5.6739e-02, 8.1431e-03, 1.5621e-01,
        4.0723e-01, 9.6782e-01, 2.7138e-02, 5.7206e-03, 7.5279e-01, 2.4701e-01,
        1.1890e-02, 1.0037e-01, 4.5112e-01, 1.4492e+00, 5.3997e-01, 5.0954e-01,
        4.3234e-02, 1.7924e+00, 1.5589e-01, 2.6706e-01, 5.3948e-02, 5.6143e-02,
        6.8188e-01, 1.1802e-02, 6.0260e-01, 2.0227e-01, 1.3838e-01, 8.3826e-02,
        3.6079e-01, 5.3247e-02, 6.6667e-01, 1.5361e+00, 3.0354e-02, 8.9931e-02,
        2.9347e-01, 3.0022e-01, 2.6416e+00, 0.0000e+00, 9.2220e-01, 1.3575e+00,
        5.8849e-01, 1.6351e-01, 1.9557e+00, 1.9061e+00, 5.3215e-02, 2.4424e+00,
        1.4181e+00, 2.5264e+00, 1.1711e-02, 1.9415e+00, 2.1326e-01, 2.0856e+00,
        3.9832e-02, 6.3539e-01, 9.9250e-04, 8.4061e-01, 4.2248e-01, 1.9659e+00,
        3.2558e-01, 7.7374e-01, 2.3061e+00, 2.8738e-01, 4.8297e-01, 1.4353e+00,
        1.2465e+00, 2.1924e-01, 1.6645e-01, 5.0196e-01, 6.3223e-01, 1.7139e-01,
        1.7240e-01, 2.5903e+00, 1.6799e+

tensor([1.4358e+00, 2.2440e-01, 9.4299e-01, 3.3737e-01, 0.0000e+00, 8.0527e-02,
        3.7701e-01, 1.6512e-01, 8.4105e-02, 4.6577e-01, 1.8275e-02, 1.6169e-01,
        2.2847e-01, 0.0000e+00, 1.3323e-01, 3.4556e-01, 5.3522e-01, 4.2191e-01,
        9.1297e-02, 8.2701e-01, 4.8211e-01, 6.3058e-01, 0.0000e+00, 0.0000e+00,
        2.8210e-01, 3.6422e-02, 4.7395e-02, 1.0991e-01, 4.2538e-01, 1.4894e-01,
        6.3885e-01, 2.9303e-01, 5.7908e-03, 3.8097e+00, 1.0312e-01, 9.2663e-02,
        1.6726e+00, 1.9208e-01, 2.9104e+00, 0.0000e+00, 5.7659e-01, 8.7978e-01,
        4.0430e-01, 1.6411e-01, 8.0618e-01, 9.6064e-01, 3.7377e-01, 1.4195e+00,
        1.5427e+00, 4.6605e-01, 5.6683e-01, 1.4538e+00, 4.3050e-01, 1.0589e+00,
        1.0866e-01, 2.5572e-02, 0.0000e+00, 1.5086e+00, 3.6656e-01, 1.9255e+00,
        2.4152e-01, 7.2502e-01, 2.0521e+00, 5.8283e-02, 2.3426e-01, 1.3483e+00,
        4.0072e-01, 0.0000e+00, 1.4372e-01, 1.6026e-01, 1.2244e+00, 0.0000e+00,
        3.4356e-01, 2.2518e+00, 1.0029e+

tensor([1.2098e-01, 5.6710e-01, 4.5912e-01, 6.6963e-02, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 3.2198e-01, 0.0000e+00, 2.2327e-03, 2.3194e-01, 1.5353e-01,
        1.5692e-01, 1.3000e-02, 2.4520e-03, 5.4555e-01, 1.5230e+00, 1.9669e-01,
        3.5374e-02, 9.1406e-02, 2.3580e-01, 4.1996e-01, 5.9927e-04, 1.2275e-01,
        5.2359e-01, 2.7097e-01, 6.6697e-01, 6.6234e-02, 6.6653e-01, 7.6735e-02,
        8.2563e-02, 4.4280e-01, 6.3934e-02, 9.9109e-01, 3.7779e-01, 4.2376e-01,
        1.3463e+00, 0.0000e+00, 2.5735e+00, 0.0000e+00, 5.9693e-01, 2.0685e-01,
        1.5802e-01, 6.1010e-02, 1.4022e+00, 6.1624e-01, 4.1726e-02, 2.1329e+00,
        1.0752e+00, 1.4025e+00, 4.9172e-01, 7.4965e-01, 1.2792e-01, 7.6816e-01,
        2.4649e-02, 2.3595e-01, 7.3164e-02, 1.6169e+00, 9.8771e-01, 1.3200e+00,
        6.9784e-01, 7.0467e-02, 7.5217e-01, 5.0295e-01, 5.7090e-02, 2.9061e-01,
        2.5660e-01, 1.8813e-01, 1.9374e-02, 6.5763e-01, 6.0851e-02, 3.1505e-02,
        1.5824e-01, 1.4278e+00, 1.2947e+

tensor([3.1510e-01, 7.8257e-01, 5.4543e-01, 1.8619e-01, 3.4061e-02, 7.3207e-03,
        8.3518e-01, 4.5125e-01, 1.8608e-01, 1.7746e-01, 1.3976e-01, 2.0070e-01,
        2.5121e-01, 2.8557e-02, 4.4484e-01, 1.0760e+00, 1.4938e+00, 6.1821e-01,
        3.0019e-01, 3.8607e-01, 1.5844e-02, 1.0409e-01, 2.0622e-03, 3.3411e-02,
        1.2251e+00, 7.7172e-02, 5.3802e-01, 5.8176e-02, 1.5590e+00, 9.3380e-02,
        1.2102e+00, 2.8653e-01, 1.1910e-01, 9.3985e-01, 5.8515e-01, 2.1172e-01,
        1.1869e+00, 3.0320e-01, 2.6213e+00, 3.8941e-02, 5.7753e-01, 1.1637e-01,
        1.2807e+00, 2.9093e-01, 1.5871e+00, 2.1664e+00, 4.5639e-01, 2.6448e+00,
        1.9928e+00, 6.2512e-01, 5.5283e-01, 5.5620e-01, 4.2160e-01, 1.5570e+00,
        4.0581e-02, 1.8464e-02, 0.0000e+00, 2.5402e+00, 1.9721e-02, 1.4063e+00,
        9.9674e-02, 1.8394e+00, 8.7321e-01, 1.9286e-02, 0.0000e+00, 4.5749e-01,
        1.4425e+00, 4.1821e-02, 6.7278e-02, 3.7145e-01, 1.2846e-01, 6.9442e-01,
        9.4971e-01, 1.0360e+00, 6.7607e-

tensor([5.8515e-01, 2.4203e-01, 1.2277e+00, 1.4731e-01, 2.9094e-02, 1.8498e-01,
        1.0701e+00, 1.2712e+00, 4.6259e-02, 2.3941e-01, 3.2168e-02, 5.1102e-01,
        1.1179e-01, 0.0000e+00, 0.0000e+00, 4.0040e-01, 1.5064e+00, 9.5400e-02,
        5.3782e-01, 2.8796e-01, 8.4389e-01, 1.5068e+00, 1.5966e-01, 6.0175e-01,
        4.0441e-01, 0.0000e+00, 2.9465e-01, 5.0933e-01, 3.4344e-01, 4.7918e-01,
        4.8365e-01, 7.5391e-01, 2.2016e-02, 1.6158e+00, 5.5853e-01, 7.2714e-01,
        1.2172e+00, 1.2092e-01, 2.5441e+00, 0.0000e+00, 7.8435e-01, 1.2554e-01,
        6.4840e-01, 2.0117e-01, 9.7896e-01, 1.9695e+00, 1.6442e-01, 1.7996e+00,
        7.8410e-01, 1.0427e+00, 1.4871e+00, 7.7548e-01, 1.2966e+00, 6.2942e-01,
        0.0000e+00, 1.1031e-01, 0.0000e+00, 6.4846e-01, 1.0647e-01, 1.5860e+00,
        2.2298e-01, 3.2624e-01, 1.7522e+00, 1.1725e-01, 1.4026e-01, 2.8376e-01,
        5.0631e-01, 3.5560e-01, 7.0534e-02, 4.4072e-01, 8.3079e-02, 0.0000e+00,
        2.6666e-01, 2.2667e+00, 1.3481e+

tensor([1.5551e-01, 1.7883e-01, 1.9973e-01, 0.0000e+00, 5.1324e-01, 7.8996e-03,
        2.2894e-02, 9.4374e-02, 5.1133e-02, 3.0951e-02, 1.5660e-01, 2.1345e-01,
        3.5165e-01, 6.3099e-02, 5.9629e-03, 6.4474e-01, 4.4620e-01, 1.9181e-01,
        1.3660e-01, 7.4809e-01, 2.3662e-01, 1.7480e+00, 8.6442e-02, 1.3150e-01,
        1.3640e-01, 3.3036e-02, 3.4686e-01, 7.0215e-01, 2.9473e-01, 1.7226e-01,
        4.5539e-01, 2.7435e-01, 0.0000e+00, 1.9084e+00, 2.7422e-01, 3.9906e-01,
        1.6854e+00, 8.3795e-04, 2.9294e+00, 0.0000e+00, 7.8020e-01, 9.2232e-01,
        4.0922e-01, 1.2830e-01, 8.1226e-01, 1.1879e+00, 3.3926e-01, 1.3196e+00,
        1.1091e+00, 5.1538e-01, 8.0904e-01, 9.2147e-01, 1.0495e+00, 9.4402e-01,
        0.0000e+00, 8.1523e-02, 0.0000e+00, 1.3197e+00, 4.2042e-01, 1.4190e+00,
        7.2314e-01, 8.2748e-02, 1.8055e+00, 4.4302e-01, 9.1961e-01, 3.9735e-01,
        3.1529e-01, 9.0418e-03, 0.0000e+00, 6.3705e-02, 5.0514e-01, 5.2643e-02,
        1.4345e-02, 1.5885e+00, 1.9464e+

tensor([1.3399e+00, 6.1214e-01, 9.0198e-01, 1.0015e-02, 1.1538e-02, 1.6687e-01,
        3.2193e-01, 9.0092e-01, 2.4206e-02, 3.0242e-01, 2.4632e-02, 0.0000e+00,
        6.9716e-02, 2.4451e-03, 2.5078e-01, 7.2415e-01, 3.4342e-01, 0.0000e+00,
        1.8519e-01, 1.7853e+00, 9.9773e-02, 7.3190e-01, 0.0000e+00, 2.0744e-01,
        1.2550e-01, 1.5750e-01, 4.5166e-01, 1.0710e+00, 2.4630e-01, 0.0000e+00,
        4.7577e-01, 2.3022e-03, 1.7350e-01, 3.6306e+00, 3.1680e-01, 6.0084e-02,
        9.0950e-01, 2.3657e-02, 3.2349e+00, 8.0183e-03, 3.3118e-01, 1.7585e+00,
        3.6933e-01, 1.7263e-01, 8.9323e-01, 1.1178e+00, 4.5807e-01, 1.7597e+00,
        1.2072e+00, 1.5689e+00, 8.9895e-02, 1.3507e+00, 1.1265e+00, 2.5428e+00,
        1.1196e-02, 2.5457e-01, 0.0000e+00, 6.0795e-01, 1.0925e-01, 1.0547e+00,
        4.5360e-01, 4.9890e-01, 2.7785e+00, 9.6438e-01, 2.8829e-01, 1.6121e+00,
        1.6925e-01, 0.0000e+00, 2.8422e-02, 1.1295e-01, 1.1820e+00, 3.9096e-02,
        0.0000e+00, 1.9232e+00, 1.6542e+

tensor([1.7126e-02, 1.0395e-01, 6.8816e-01, 1.4246e-04, 4.8699e-02, 2.3191e-02,
        9.7427e-01, 3.9189e-03, 3.6054e-01, 8.5843e-02, 8.6688e-01, 4.2219e-01,
        6.7624e-02, 5.3222e-02, 9.1123e-02, 1.2909e+00, 5.1750e-01, 3.6014e-01,
        1.9454e-01, 5.7452e-01, 3.7697e-01, 8.8674e-01, 1.9605e-01, 2.6637e-01,
        6.5432e-01, 6.1411e-01, 2.5457e-01, 8.7544e-01, 5.2271e-01, 1.7397e-03,
        4.4295e-01, 3.3972e-01, 4.6637e-01, 1.4799e+00, 0.0000e+00, 2.7531e-01,
        9.0231e-01, 1.4103e-01, 2.9640e+00, 0.0000e+00, 2.3690e-01, 1.1546e+00,
        6.6062e-01, 4.3749e-01, 2.2315e+00, 8.2541e-01, 4.6442e-01, 2.3737e+00,
        2.5723e-01, 2.4584e+00, 1.2885e-01, 1.0365e+00, 3.4942e-01, 1.6523e+00,
        1.4947e-01, 3.6216e-03, 3.1575e-02, 1.1777e+00, 9.7168e-01, 1.0377e+00,
        3.1713e-01, 1.3305e+00, 1.4686e+00, 9.5119e-01, 2.4846e-01, 8.3472e-02,
        3.9713e-01, 0.0000e+00, 0.0000e+00, 2.5812e-01, 2.0896e-01, 1.0669e-01,
        2.2903e-01, 2.3940e+00, 1.0393e+

tensor([2.7458e-01, 1.4777e+00, 8.4967e-01, 5.1127e-03, 0.0000e+00, 4.0934e-02,
        1.0710e+00, 1.1200e-01, 0.0000e+00, 1.1908e-01, 9.8957e-01, 1.3893e-01,
        5.6472e-03, 0.0000e+00, 1.9382e-01, 1.1310e+00, 1.4980e+00, 3.6953e-01,
        1.1604e+00, 1.3989e+00, 0.0000e+00, 1.0056e-02, 9.3163e-02, 4.9517e-01,
        2.9052e-01, 3.4118e-01, 1.2218e-01, 5.8845e-01, 3.8624e-01, 0.0000e+00,
        2.2056e-01, 7.4293e-02, 8.2434e-01, 1.4102e+00, 4.9745e-02, 0.0000e+00,
        1.1437e+00, 7.6352e-02, 1.3545e+00, 0.0000e+00, 2.4911e-02, 9.0797e-01,
        6.4916e-01, 9.8280e-02, 2.4310e+00, 1.4637e+00, 1.0025e-01, 6.0531e-01,
        7.9499e-01, 2.8975e+00, 1.6573e-01, 9.7051e-01, 0.0000e+00, 1.3074e+00,
        1.0093e-01, 1.3243e+00, 0.0000e+00, 1.8701e+00, 4.0801e-02, 2.0616e+00,
        5.5944e-01, 1.0768e-01, 2.1902e+00, 9.3079e-01, 6.3013e-03, 1.5412e+00,
        2.7794e+00, 0.0000e+00, 0.0000e+00, 1.3920e+00, 7.4651e-02, 8.7626e-01,
        3.3624e-01, 1.2453e+00, 6.3647e-

tensor([1.0015e+00, 8.8258e-02, 9.9608e-01, 6.6486e-01, 0.0000e+00, 0.0000e+00,
        2.5105e-01, 5.2045e-01, 2.6894e-02, 0.0000e+00, 3.3481e-01, 4.8973e-02,
        3.9689e-01, 7.2633e-01, 3.8792e-02, 1.1100e+00, 5.7520e-01, 4.8917e-01,
        3.0152e-02, 1.2882e-01, 3.9302e-02, 5.8735e-01, 3.1338e-01, 2.2679e-01,
        3.6111e-01, 1.1016e-01, 3.3885e-01, 0.0000e+00, 2.5037e-01, 1.4396e-01,
        1.3430e-01, 1.4454e-01, 2.1279e-01, 1.4653e+00, 4.3689e-01, 4.0642e-01,
        1.3719e+00, 2.4866e-02, 3.2220e+00, 0.0000e+00, 7.3279e-01, 1.2159e+00,
        1.0684e+00, 1.5822e-01, 1.0008e+00, 2.0524e+00, 8.5440e-02, 7.4052e-01,
        6.7355e-01, 1.3760e+00, 3.6027e-01, 9.6005e-01, 6.6396e-01, 1.1087e+00,
        5.8458e-02, 6.8182e-01, 5.5236e-01, 1.2187e+00, 2.4551e-01, 1.4456e+00,
        2.1032e-01, 1.6601e-01, 1.8424e+00, 1.1371e+00, 9.5113e-01, 1.3602e+00,
        7.8177e-01, 6.9996e-01, 1.3759e-01, 5.4393e-01, 5.7534e-01, 2.9932e-01,
        3.3970e-02, 1.7736e+00, 1.2190e+

tensor([4.1405e-01, 1.2828e+00, 1.4109e-01, 1.5019e-01, 2.5281e-01, 8.8187e-03,
        3.1360e-01, 1.5921e+00, 1.6117e-01, 2.0127e-01, 2.4704e-01, 0.0000e+00,
        2.9657e-01, 3.9069e-02, 3.8762e-02, 5.0923e-01, 7.9762e-01, 1.7773e-01,
        1.1523e-01, 5.5972e-01, 2.4302e-02, 1.3289e+00, 1.7532e-01, 1.4226e-01,
        6.0433e-02, 3.6451e-01, 3.3814e-01, 3.1042e-01, 2.5420e-01, 2.0943e-01,
        3.1386e-01, 4.4781e-01, 1.0405e-01, 3.3265e+00, 1.6520e+00, 4.6886e-01,
        1.5534e+00, 9.4545e-03, 2.1916e+00, 1.7443e-01, 1.0536e+00, 1.9656e-01,
        1.5483e+00, 2.9825e-01, 1.1261e+00, 2.4307e+00, 2.7080e-01, 1.4342e+00,
        2.0846e+00, 6.3053e-01, 3.5291e-01, 8.7022e-01, 1.1476e+00, 9.2931e-01,
        0.0000e+00, 9.2366e-02, 2.0223e-03, 1.3303e+00, 8.0209e-01, 1.8557e+00,
        8.5032e-01, 6.2507e-01, 1.9872e+00, 5.5709e-02, 1.4761e-01, 7.1991e-01,
        4.3386e-01, 6.2769e-02, 4.7707e-02, 1.2852e-01, 2.6167e-01, 0.0000e+00,
        0.0000e+00, 2.6404e+00, 1.8643e+

tensor([1.0497e+00, 2.4330e-01, 9.3094e-01, 0.0000e+00, 0.0000e+00, 1.7004e-01,
        9.8136e-02, 9.2069e-01, 0.0000e+00, 1.0555e-01, 8.3575e-03, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 2.2597e-01, 6.1493e-01, 5.6238e-01, 5.6128e-02,
        1.8663e-02, 2.4689e+00, 3.4038e-03, 3.7724e-01, 6.0216e-03, 4.8109e-02,
        1.3050e-01, 0.0000e+00, 1.7424e-01, 6.2209e-01, 3.5884e-01, 1.5779e-03,
        2.0385e-01, 2.4337e-02, 2.0141e-01, 2.1474e+00, 2.9220e-02, 2.9410e-02,
        6.3008e-01, 3.4331e-02, 3.4016e+00, 0.0000e+00, 3.1280e-01, 1.3853e+00,
        3.7532e-01, 4.6026e-02, 1.1521e+00, 1.3569e+00, 2.7290e-01, 1.6783e+00,
        3.6579e-01, 5.1361e-01, 3.2304e-02, 1.8068e+00, 1.6463e-01, 2.2307e+00,
        0.0000e+00, 3.6869e-01, 0.0000e+00, 3.4826e-01, 0.0000e+00, 1.3021e+00,
        3.3832e-01, 4.8946e-01, 2.6107e+00, 5.8863e-03, 1.7266e-01, 2.0096e+00,
        4.9566e-01, 7.6016e-03, 3.2505e-01, 0.0000e+00, 7.4407e-01, 9.6031e-01,
        0.0000e+00, 1.5711e+00, 1.0377e+

tensor([8.6593e-03, 3.7152e-01, 3.5168e-01, 1.5774e-02, 2.0181e-01, 7.1147e-02,
        3.2923e-02, 6.6533e-01, 9.5889e-02, 7.1251e-02, 2.6756e-01, 2.4567e-01,
        1.7927e-01, 2.1122e-01, 0.0000e+00, 8.0344e-01, 1.2892e+00, 1.0652e-01,
        0.0000e+00, 7.2576e-02, 2.7506e-01, 4.9451e-01, 3.6958e-01, 4.5169e-01,
        9.3661e-01, 3.0209e-01, 3.2263e-01, 4.6680e-01, 6.8054e-01, 2.6392e-01,
        4.7568e-01, 3.3167e-01, 9.7958e-02, 1.5630e+00, 4.3771e-01, 2.7792e-01,
        5.2208e-01, 0.0000e+00, 2.1243e+00, 7.1741e-02, 3.0455e-01, 8.0423e-02,
        9.2879e-01, 3.1287e-01, 1.1993e+00, 1.8824e+00, 6.1982e-02, 2.2704e+00,
        1.1880e+00, 1.0820e+00, 9.5536e-02, 4.6318e-02, 2.7544e-01, 8.5446e-01,
        0.0000e+00, 6.2213e-01, 2.8967e-01, 9.8519e-01, 6.2552e-01, 1.7022e+00,
        4.6541e-01, 1.4929e-01, 1.7034e+00, 2.0536e-01, 1.4747e-01, 4.5989e-01,
        1.9540e-01, 1.2539e-01, 4.7251e-02, 9.6876e-02, 2.6202e-01, 3.2761e-02,
        1.7048e-01, 1.1382e+00, 1.4425e+

tensor([7.9029e-02, 1.6768e+00, 7.5217e-01, 0.0000e+00, 2.2376e-01, 1.1086e-01,
        1.6549e-02, 1.4982e+00, 1.4459e-02, 2.2070e-03, 4.6190e-01, 1.5167e-02,
        1.1555e-01, 5.9082e-02, 2.6751e-01, 1.3154e+00, 8.9103e-01, 3.3265e-02,
        2.0796e-02, 2.2748e-01, 1.3132e-01, 1.3183e+00, 3.5079e-01, 3.8148e-01,
        7.9550e-02, 9.8375e-02, 4.5805e-01, 5.9830e-01, 7.5940e-01, 5.5294e-03,
        1.1080e+00, 2.1768e-01, 9.9232e-03, 1.5654e+00, 5.4986e-01, 1.0528e-01,
        1.0253e+00, 2.4651e-02, 2.4492e+00, 0.0000e+00, 1.4688e+00, 8.7386e-01,
        5.3775e-01, 1.1880e-01, 1.3557e+00, 2.4723e+00, 1.5392e-01, 2.5902e+00,
        1.0748e+00, 1.6066e+00, 1.9591e-01, 1.2954e+00, 8.9769e-01, 9.3875e-01,
        0.0000e+00, 2.4125e-01, 3.8698e-02, 8.2761e-01, 7.0865e-01, 1.1774e+00,
        9.1485e-01, 3.2833e-01, 2.2724e+00, 4.5556e-01, 2.3092e-01, 4.4463e-01,
        7.3504e-01, 1.4700e-01, 1.5316e-01, 4.0108e-01, 1.6475e-01, 4.0708e-02,
        9.0331e-03, 1.4792e+00, 1.6866e+

tensor([2.4842e+00, 5.7157e-01, 2.1376e-02, 0.0000e+00, 0.0000e+00, 3.6630e-01,
        7.3388e-03, 5.1123e-01, 9.5241e-03, 3.4082e-02, 2.4507e-01, 6.0492e-02,
        5.8293e-02, 6.8348e-02, 1.0435e+00, 2.6145e-02, 1.9070e-01, 0.0000e+00,
        8.0326e-02, 1.3624e+00, 6.4411e-01, 8.4794e-02, 2.2859e-01, 1.2600e-02,
        7.7459e-01, 0.0000e+00, 4.2502e-01, 4.2294e-02, 5.2154e-01, 3.4221e-01,
        5.1261e-01, 1.3491e+00, 1.4593e+00, 1.5642e+00, 3.1841e-02, 0.0000e+00,
        1.9705e-01, 3.8129e-01, 1.7871e+00, 1.0101e-02, 8.3609e-01, 1.8361e+00,
        1.1198e+00, 3.7650e-01, 2.2212e+00, 1.1103e+00, 3.8858e-02, 1.8352e+00,
        4.9154e-01, 3.8070e+00, 1.4792e+00, 3.3440e-01, 9.8720e-01, 2.0938e+00,
        7.3127e-02, 9.4541e-02, 1.3051e-01, 2.6321e+00, 1.6722e-01, 1.9440e+00,
        3.1337e-01, 1.2183e+00, 6.5610e-01, 1.6009e+00, 3.5630e-01, 3.9498e-02,
        4.2157e-01, 0.0000e+00, 4.5846e-01, 1.0696e-01, 3.8223e-01, 0.0000e+00,
        1.0793e+00, 2.6029e+00, 7.9999e-

tensor([1.9684e+00, 4.6876e-01, 8.4112e-01, 1.1122e-02, 5.2298e-03, 1.2792e-01,
        1.5137e+00, 4.2804e-01, 1.4233e-01, 2.5870e-01, 1.4539e-01, 8.9717e-02,
        1.2939e-01, 2.3081e-01, 3.2928e-01, 1.5646e+00, 1.3140e+00, 2.2426e-02,
        7.0252e-01, 2.1037e+00, 3.0596e-01, 4.2851e-02, 1.9989e-01, 1.0879e-01,
        8.4592e-01, 1.9058e-01, 1.1100e-01, 2.9851e-01, 8.7250e-01, 0.0000e+00,
        7.6988e-01, 2.5285e-01, 1.4866e-01, 3.4234e+00, 0.0000e+00, 2.5952e-02,
        3.5972e-01, 1.3227e-01, 2.6107e+00, 4.4613e-01, 7.3540e-02, 6.4707e-01,
        1.0202e+00, 2.6766e-01, 1.4056e+00, 3.2552e+00, 6.3359e-03, 2.5619e+00,
        4.6145e-01, 2.3201e+00, 7.1634e-02, 1.1863e+00, 1.4435e+00, 1.6697e+00,
        0.0000e+00, 5.9587e-01, 1.0763e-01, 1.0489e+00, 3.5546e-01, 1.6639e+00,
        1.7555e-01, 6.1146e-01, 2.3844e+00, 6.6063e-01, 1.3513e-02, 7.6467e-01,
        8.4727e-01, 9.5453e-03, 0.0000e+00, 7.5468e-02, 3.3568e-01, 5.9639e-02,
        1.3894e-01, 3.0510e+00, 7.9560e-

tensor([2.4590e-01, 4.2981e-01, 5.0842e-01, 3.2953e-02, 7.4971e-02, 2.6454e-02,
        5.6260e-01, 5.5700e-01, 7.7898e-02, 1.8081e-02, 3.2406e-01, 3.1665e-01,
        0.0000e+00, 6.0134e-02, 7.9516e-02, 7.4897e-01, 4.9935e-01, 1.8009e-01,
        1.5022e-01, 1.3862e+00, 5.1212e-01, 1.9779e-02, 1.3323e-01, 2.3508e-02,
        1.0964e+00, 0.0000e+00, 1.6219e-01, 7.7989e-01, 5.0710e-01, 2.4397e-01,
        7.4290e-01, 1.0466e+00, 7.4887e-01, 1.6287e+00, 6.7266e-02, 5.0312e-02,
        5.2596e-01, 4.7146e-02, 8.4644e-01, 0.0000e+00, 3.6965e-01, 2.2099e-01,
        1.3687e+00, 3.4900e-01, 1.9863e+00, 1.3668e+00, 8.6823e-02, 1.4897e+00,
        1.1105e+00, 3.5947e+00, 4.3957e-01, 1.3029e-01, 3.8160e-01, 8.5454e-01,
        0.0000e+00, 6.1776e-01, 1.2513e-02, 2.4087e+00, 1.4947e-01, 1.6202e+00,
        2.7516e-01, 1.1135e+00, 1.8748e+00, 1.3926e+00, 2.9185e-01, 9.9592e-02,
        9.2605e-01, 0.0000e+00, 0.0000e+00, 4.0078e-01, 4.0141e-01, 3.2959e-01,
        4.4657e-01, 2.9656e+00, 9.4292e-

tensor([8.4131e-01, 4.1303e-01, 7.4612e-01, 0.0000e+00, 2.0016e-01, 0.0000e+00,
        8.0653e-02, 1.2134e-02, 0.0000e+00, 5.1919e-02, 1.9107e-01, 1.0169e-02,
        4.1748e-04, 0.0000e+00, 1.8093e-01, 4.1177e-01, 8.3978e-01, 4.8409e-02,
        9.6720e-02, 1.3895e+00, 0.0000e+00, 5.8173e-01, 4.7907e-02, 6.8268e-03,
        6.7802e-01, 0.0000e+00, 6.8680e-01, 0.0000e+00, 7.2305e-01, 6.4694e-04,
        1.6690e-01, 1.5381e+00, 1.1485e+00, 2.0027e+00, 5.2097e-01, 1.6063e-01,
        8.1987e-01, 0.0000e+00, 1.3553e+00, 7.6623e-02, 6.3145e-01, 6.9275e-01,
        4.1493e-01, 1.2342e-02, 1.8765e+00, 1.5044e+00, 3.2220e-02, 6.4344e-01,
        1.4261e+00, 4.0826e+00, 1.9896e-02, 9.5946e-01, 5.7080e-01, 1.0094e+00,
        0.0000e+00, 1.1248e-01, 2.6487e-01, 2.0012e+00, 4.6546e-01, 1.6891e+00,
        1.4844e-01, 3.0408e-01, 1.4096e+00, 6.4545e-02, 0.0000e+00, 6.4287e-01,
        7.6621e-01, 0.0000e+00, 8.1730e-03, 2.8699e-01, 4.9066e-01, 8.6223e-03,
        2.0056e-01, 3.6321e+00, 1.5128e+

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 7.5284e-02, 0.0000e+00, 4.9152e-01,
        4.7061e-01, 4.3663e+00, 3.8290e-01, 2.8501e-03, 1.4280e-03, 8.6560e-02,
        0.0000e+00, 6.3701e-04, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5639e+00,
        1.6239e-01, 2.3242e-02, 3.9855e-02, 1.2880e+00, 2.4051e-03, 0.0000e+00,
        8.1616e-02, 2.3130e-02, 2.0957e-01, 0.0000e+00, 2.6232e-01, 5.4061e-01,
        2.0224e-03, 2.9990e-01, 6.8183e-02, 4.9672e-01, 1.5829e-01, 2.1604e-01,
        7.6264e-01, 9.3135e-02, 2.3422e-04, 3.0326e-01, 3.3828e-03, 0.0000e+00,
        9.9503e-01, 2.0293e+00, 5.7889e-01, 8.2593e-04, 1.2383e-01, 1.4249e-01,
        3.0226e-01, 3.2815e-01, 7.4375e-01, 0.0000e+00, 6.7731e-02, 6.1603e-04,
        0.0000e+00, 1.2758e-02, 4.7874e-01, 1.7830e+00, 7.7750e-01, 2.0010e-01,
        1.0839e+00, 1.2117e-03, 1.0925e-01, 0.0000e+00, 4.8858e-02, 1.7961e-01,
        3.0016e-02, 2.1937e-01, 1.3483e-01, 7.0640e-01, 8.4350e-02, 2.2053e-01,
        0.0000e+00, 4.1946e-01, 1.0059e+

tensor([2.3214e-01, 1.0479e+00, 9.1295e-01, 1.5611e-03, 3.6018e-01, 5.9331e-01,
        2.1669e-01, 1.2584e+00, 2.2979e-01, 1.3495e-02, 6.6292e-01, 5.0996e-01,
        2.5833e-01, 4.7968e-01, 1.9524e-01, 1.8217e+00, 8.8965e-01, 2.3385e-01,
        2.8878e-02, 6.5798e-01, 4.3542e-02, 7.2137e-01, 1.9989e-01, 6.7514e-01,
        1.0588e+00, 9.5926e-03, 6.9828e-01, 1.2773e-01, 5.0848e-01, 5.0207e-02,
        5.5310e-01, 4.9929e-01, 4.4793e-02, 9.7499e-01, 2.7202e-01, 5.3942e-02,
        1.4834e+00, 4.4694e-01, 4.1024e+00, 1.1918e-02, 1.3330e+00, 7.3084e-01,
        8.9745e-01, 1.9957e-01, 2.1903e+00, 2.6455e+00, 1.7506e-02, 1.1462e+00,
        1.4822e+00, 1.3905e+00, 6.7008e-01, 1.7429e+00, 1.1463e+00, 1.1570e+00,
        4.1713e-02, 6.0075e-02, 1.6918e-01, 4.0675e-01, 5.2242e-01, 2.1129e+00,
        1.2009e-01, 5.6790e-01, 2.7627e+00, 8.0788e-01, 3.4170e-01, 3.5695e-01,
        1.7049e+00, 4.4667e-01, 0.0000e+00, 3.0603e-01, 1.2712e+00, 3.4035e-01,
        5.1943e-03, 1.4113e+00, 1.3036e+

tensor([5.2002e-01, 8.0225e-01, 8.9415e-01, 7.0228e-02, 0.0000e+00, 1.2035e-02,
        2.3140e-01, 4.6775e-01, 1.7926e-02, 1.1690e-01, 5.8784e-01, 5.3466e-01,
        1.4676e-01, 3.2832e-02, 3.4453e-02, 2.0324e+00, 1.5827e+00, 4.4898e-03,
        3.8272e-02, 8.2132e-01, 0.0000e+00, 4.5226e-01, 1.4913e-02, 7.6779e-01,
        9.8372e-01, 0.0000e+00, 2.7568e-01, 4.2900e-01, 8.2054e-01, 2.1619e-01,
        3.3803e-01, 4.4896e-01, 2.2988e-01, 1.2142e+00, 5.8627e-01, 1.4274e-01,
        8.6238e-01, 4.6956e-01, 4.5679e+00, 1.4153e-03, 8.5723e-01, 1.2522e+00,
        1.1349e+00, 2.9917e-01, 2.9211e+00, 1.7813e+00, 1.5451e-01, 1.6283e+00,
        1.2830e+00, 1.1768e+00, 9.2325e-02, 2.1626e+00, 9.5154e-01, 2.6875e+00,
        1.5636e-02, 1.0661e+00, 1.3404e-01, 8.9553e-01, 2.1170e-02, 2.2640e+00,
        3.1583e-01, 4.2469e-01, 2.5622e+00, 4.6687e-01, 8.2670e-01, 6.1624e-01,
        3.4629e-01, 4.4820e-03, 7.0369e-02, 5.9154e-01, 1.6370e-01, 7.2521e-02,
        2.3625e-01, 2.4873e+00, 1.4773e+

KeyboardInterrupt: 

In [14]:
# torch.save(model.state_dict(), 'dl64b_v2_1000.pt')